#######################################################
#                                                     #
#   sdScreenShare - Um plugin simples de ScreenShare  #
#                                                     #
#     Dúvidas? me chame no discord! - Sudano#0001     #
#        Source - https://github.com/sudanoj          #
#                                                     #
#######################################################


# Nesse campo, coloque o nome do mundo PADRÃO, para quando o jogador sair do ScreenShare (Ele é teleportado para o Spawn)
Mundo: 'world'

# Nesse campo, coloque o nome do mundo SCREENSHARE, para quando o jogador entrar no ScreenShare (Ele é teleportado para o Spawn, utilize /setworldspawn)
MundoSS: 'ssworld'


EntrouSS:
- ' '
- '&cVocê foi teleportado para a &lSCREENSHARE&c!'
- '&cCaso você desconecte do servidor, será &lAUTOMATICAMENTE&c banido!'
- '&cBaixe o aplicativo AnyDesk, e siga todos os passos que o staff falar!'
- ' '

SaiuSS:
- ' '
- '&cVocê foi retirado da &lSCREENSHARE&c!'
- '&cObrigado por cooperar com o servidor, e nos desculpe pelo incomodo!'
- '&cApenas estamos tentando manter a comunidade segura!'
- ' '

# Utilize {player} para colocar o nome do jogador!
DesconectouSS:
- ' '
- '&cO jogador &l{player} &cdesconectou na &lSCREENSHARE!'
- ' '

# Utilize apenas 'true' ou 'false'
# 'true' - Vai banir o jogador ao deslogar na ScreenShare
# 'false' - Não vai banir o jogador ao deslogar na ScreenShare
BanirDesconectar: 'true'

# Comando utilizado para banir (Utilizado pelo Console)
# Utilize {player} para colocar o nome do jogador!
ComandoBan: '/ban {player} desconectar na ss!'













